
init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: cat /etc/environment
 
test_script:
 - sh: export DOTNET_PRINT_TELEMETRY_MESSAGE=false
 - sh: unset DOTNET_CLI_TELEMETRY_OPTOUT
 - sh: echo $DOTNET_CLI_TELEMETRY_OPTOUT
 - sh: dotnet -d build
 
build: off
