
init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: cat /etc/environment
 
test_script:
 - sh: echo $DOTNET_PRINT_TELEMETRY_MESSAGE
 - sh: echo $DOTNET_CLI_TELEMETRY_OPTOUT
 - sh: dotnet build
 
build: off
