
init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: cat /etc/environment
 
test_script:
 - sh: echo $DOTNET_PRINT_TELEMETRY_MESSAGE
 - sh: echo $DOTNET_CLI_TELEMETRY_OPTOUT
 - sh: |
    OUTPUT=$(dotnet build || true)
    echo "${OUTPUT}"
    while read -r line; do
      if [[ $line =~ ^Telemetry$ ]]; then
        echo "There is Telemetry message in dotnet output"
        return 1
      fi
    done <<< "${OUTPUT}"
 
build: off
