
init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 
test_script:
 - sh: export DOTNET_CLI_TELEMETRY_OPTOUT=true
 - sh: DOTNET_CLI_TELEMETRY_OPTOUT=true dotnet -d build
 
build: off
